name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Use reusable workflow
        uses: srinivasamoorthy11/Task1/.github/workflows/re-workflow1.yml@main
        with:
          name: 'Alice'
          message: 'Good morning'
          secret_name: 'my-secret'
